---
title: 从零开始写一个promise
date: 2021-07-05 14:41:30
permalink: /pages/b7756f/
categories:
  - 前端
  - JavaScript文章
tags:
  - promise
---

## 1 基础版本

### 1.1 目标

- 可以创建promise对象实例
- promise实例传入的异步方法执行成功就执行注册的成功回调函数，失败就执行注册的失败回调函数

### 1.2 实现

```
function MyPromise(fn){
    let self = this     // 缓存当前promise实例
    self.value = null   // 成功时的值
    self.error = null   // 失败时的原因
    self.onFulfuilled = null    // 成功的回调函数
    self.onRejected = null    // 失败的回调函数

    function resolve(value){
        self.value = value
        self.onFulfuilled(self.value)   // resolve时执行成功回调
    }

    function reject(error){
        self.error = error
        self.onRejected(self.error)     // reject时执行失败回调
    }

    fn(resolve,reject)
}

MyPromise.prototype.then = function(onFulfuilled,onRejected){
    // 在这里给promis实例注册成功和失败回调
    this.onFulfuilled = onFulfuilled
    this.onRejected = onRejected
}

module.exports = MyPromise
```

## 2 支持同步任务

我们在使用es6 的promise时，可以传入一个异步任务，也可以传入一个同步任务，但是我们的上面基础版代码并不支持同步任务。

为什么呢？因为是同步任务，所以当我们的promise实例reslove时，它的then方法还没执行到，所以回调函数还没注册上，这时reslove中调用成功回调肯定会报错的。

### 2.1 目标

- 使promise支持同步方法

### 2.2 实现

```
function resolve(value) {
    //利用setTimeout特性将具体执行放到then之后
    setTimeout(() => {
        self.value = value;
        self.onFulfilled(self.value)
    })
}

function reject(error) {
    setTimeout(() => {
        self.error = error;
        self.onRejected(self.error)
    })
}
```

实现很简单，就是在reslove和reject里面用setTimeout进行包裹，使其到then方法执行之后再去执行，这样我们就让promise支持传入同步方法

## 3 支持三种状态

- promise有三种状态:pending（进行中）、fulfilled（已成功）和rejected（已失败）
- promise一旦状态改变，就不会再变
- 如果改变已经发生了，你再对promise对象添加回调函数，也会立即得到这个结果

### 3.1 目标

1. 实现promise的三种状态
2. 实现promise对象的状态改变。从pending->fulfilled和从pending->rejected
3. 实现一旦promise状态改变，再对promise对象添加回调函数，也会立即得到这个结果

### 3.2 实现

```
// 定义三种状态
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'
function MyPromise(fn){
    let self = this     // 缓存当前promise实例
    self.value = null   // 成功时的值
    self.error = null   // 失败时的原因
    self.status = PENDING
    self.onFulfuilled = null    // 成功的回调函数
    self.onRejected = null    // 失败的回调函数

    function resolve(value){
         // 如果状态是pending才去修改状态为fulfilled并执行成功逻辑
        if(self.status === PENDING){
            // 利用setTimeout特性将具体执行放到then之后
            setTimeout(()=>{
                self.status = FULFILLED
                self.value = value
                self.onFulfuilled(self.value)   // resolve时执行成功回调
            })
        }
    }

    function reject(error){
        // 如果状态是pending才去修改状态为rejected并执行失败逻辑
        if(self.status === REJECTED){
            setTimeout(()=>{
                self.status = REJECTED
                self.error = error
                self.onRejected(self.error)     // reject时执行失败回调
            })
        }
    }

    fn(resolve,reject)
}

MyPromise.prototype.then = function(onFulfuilled,onRejected){
    if (this.status === PENDING){
        // 在这里给promis实例注册成功和失败回调
        this.onFulfuilled = onFulfuilled
        this.onRejected = onRejected
    } else if(this.status === FULFILLED){
        //如果状态是fulfilled，直接执行成功回调，并将成功值传入
        onFulfilled(this.value)
    } else {
        //如果状态是rejected，直接执行失败回调，并将失败原因传入
        onRejected(this.error)
    }
}

module.exports = MyPromise
```

## 4 支持链式操作

`promise.then(f1).then(f2).then(f3)`

### 4.1 目标

- 使promise支持链式操作

### 4.2 实现

想支持链式操作，首先存储回调时要改为使用数组

```
self.onFulfilledCallbacks = [];
self.onRejectedCallbacks = [];
```

执行回调时，也要改成遍历回调数组执行回调函数

```
self.onFulfilledCallbacks.forEach((callback) => callback(self.value));
```

最后，then方法也要改一下,只需要在最后一行加一个return this即可，这其实和jQuery链式操作的原理一致，每次调用完方法都返回自身实例，后面的方法也是实例的方法，所以可以继续执行。

```
MyPromise.prototype.then = function(onFulfilled, onRejected) {
    if (this.status === PENDING) {
        this.onFulfilledCallbacks.push(onFulfilled);
        this.onRejectedCallbacks.push(onRejected);
    } else if (this.status === FULFILLED) {
        onFulfilled(this.value)
    } else {
        onRejected(this.error)
    }
    return this;
}
```

## 5 支持串行异步任务

### 5.1 目标

- 使promise支持串行异步操作

### 5.2 实现

要想实现异步操作串行，我们不能将回调函数都注册在初始promise的onFulfilledCallbacks里面，而要将每个回调函数注册在对应的异步操作promise的onFulfilledCallbacks里面

如何既能保持这种链式写法的同时又能使异步操作衔接执行呢？我们其实让then方法最后不再返回自身实例，而是返回一个新的promise即可，我们可以叫它bridgePromise，它最大的作用就是衔接后续操作

```
// 定义三种状态
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'
function MyPromise(fn) {
    let self = this     // 缓存当前promise实例
    self.value = null   // 成功时的值
    self.error = null   // 失败时的原因
    self.status = PENDING
    self.onFulfilledCallbacks = []    // 成功的回调函数
    self.onRejectedCallbacks = []    // 失败的回调函数

    function resolve(value) {
        // 如果状态是pending才去修改状态为fulfilled并执行成功逻辑
        if (self.status === PENDING) {
            // 利用setTimeout特性将具体执行放到then之后
            setTimeout(() => {
                self.status = FULFILLED
                self.value = value
                self.onFulfilledCallbacks.forEach((callback) => callback(self.value))   // resolve时执行成功回调
            })
        }
    }

    function reject(error) {
        // 如果状态是pending才去修改状态为rejected并执行失败逻辑
        if (self.status === REJECTED) {
            setTimeout(() => {
                self.status = REJECTED
                self.error = error
                self.onRejectedCallbacks.forEach((callback) => callback(self.value))     // reject时执行失败回调
            })
        }
    }

    fn(resolve, reject)
}
//用来解析回调函数的返回值x，x可能是普通值也可能是个promise对象
function resolvePromise(bridgePromise, x, resolve, reject) {
    //如果x是一个promise
    if (x instanceof MyPromise) {
        //如果这个promise是pending状态，就在它的then方法里继续执行resolvePromise解析它的结果，直到返回值不是一个pending状态的promise为止
        if (x.status === PENDING) {
            x.then(y => {
                resolvePromise(bridgePromise, y, resolve, reject);
            }, error => {
                reject(error);
            });
        } else {
            x.then(resolve, reject);
        }
        //如果x是一个普通值，就让bridgePromise的状态fulfilled，并把这个值传递下去
    } else {
        resolve(x);
    }
}

MyPromise.prototype.then = function (onFulfilled, onRejected) {
    const self = this;
    let bridgePromise;
    //防止使用者不传成功或失败回调函数，所以成功失败回调都给了默认回调函数
    onFulfilled = typeof onFulfilled === "function" ? onFulfilled : value => value;
    onRejected = typeof onRejected === "function" ? onRejected : error => { throw error };

    if (self.status === FULFILLED) {
        return bridgePromise = new MyPromise((resolve, reject) => {
            setTimeout(() => {
                try {
                    let x = onFulfilled(self.value);
                    resolvePromise(bridgePromise, x, resolve, reject);
                } catch (e) {
                    reject(e);
                }
            });
        })
    }
    if (self.status === REJECTED) {
        return bridgePromise = new MyPromise((resolve, reject) => {
            setTimeout(() => {
                try {
                    let x = onRejected(self.error);
                    resolvePromise(bridgePromise, x, resolve, reject);
                } catch (e) {
                    reject(e);
                }
            });
        });
    }
    if (self.status === PENDING) {
        return bridgePromise = new MyPromise((resolve, reject) => {
            self.onFulfilledCallbacks.push((value) => {
                try {
                    let x = onFulfilled(value);
                    resolvePromise(bridgePromise, x, resolve, reject);
                } catch (e) {
                    reject(e);
                }
            });
            self.onRejectedCallbacks.push((error) => {
                try {
                    let x = onRejected(error);
                    resolvePromise(bridgePromise, x, resolve, reject);
                } catch (e) {
                    reject(e);
                }
            });
        });
    }
}
//catch方法其实是个语法糖，就是只传onRejected不传onFulfilled的then方法
MyPromise.prototype.catch = function (onRejected) {
    return this.then(null, onRejected);
}
module.exports = MyPromise
```

## 6 达到Promises/A+规范

### 6.1 目标

- 使promise达到Promises/A+规范，通过promises-aplus-tests的完整测试

### 6.2 实现

```
const PENDING = "pending";
const FULFILLED = "fulfilled";
const REJECTED = "rejected";

function MyPromise(fn) {
    const self = this;
    self.value = null;
    self.error = null;
    self.status = PENDING;
    self.onFulfilledCallbacks = [];
    self.onRejectedCallbacks = [];

    function resolve(value) {
        if (value instanceof MyPromise) {
            return value.then(resolve, reject);
        }
        if (self.status === PENDING) {
            setTimeout(() => {
                self.status = FULFILLED;
                self.value = value;
                self.onFulfilledCallbacks.forEach((callback) => callback(self.value));
            }, 0)
        }
    }

    function reject(error) {
        if (self.status === PENDING) {
            setTimeout(function() {
                self.status = REJECTED;
                self.error = error;
                self.onRejectedCallbacks.forEach((callback) => callback(self.error));
            }, 0)
        }
    }
    try {
        fn(resolve, reject);
    } catch (e) {
        reject(e);
    }
}

function resolvePromise(bridgepromise, x, resolve, reject) {
    //2.3.1规范，避免循环引用
    if (bridgepromise === x) {
        return reject(new TypeError('Circular reference'));
    }
    let called = false;
    //这个判断分支其实已经可以删除，用下面那个分支代替，因为promise也是一个thenable对象
    if (x instanceof MyPromise) {
        if (x.status === PENDING) {
            x.then(y => {
                resolvePromise(bridgepromise, y, resolve, reject);
            }, error => {
                reject(error);
            });
        } else {
            x.then(resolve, reject);
        }
        // 2.3.3规范，如果 x 为对象或者函数
    } else if (x != null && ((typeof x === 'object') || (typeof x === 'function'))) {
        try {
            // 是否是thenable对象（具有then方法的对象/函数）
            //2.3.3.1 将 then 赋为 x.then
            let then = x.then;
            if (typeof then === 'function') {
            //2.3.3.3 如果 then 是一个函数，以x为this调用then函数，且第一个参数是resolvePromise，第二个参数是rejectPromise
                then.call(x, y => {
                    if (called) return;
                    called = true;
                    resolvePromise(bridgepromise, y, resolve, reject);
                }, error => {
                    if (called) return;
                    called = true;
                    reject(error);
                })
            } else {
            //2.3.3.4 如果 then不是一个函数，则 以x为值fulfill promise。
                resolve(x);
            }
        } catch (e) {
        //2.3.3.2 如果在取x.then值时抛出了异常，则以这个异常做为原因将promise拒绝。
            if (called) return;
            called = true;
            reject(e);
        }
    } else {
        resolve(x);
    }
}

MyPromise.prototype.then = function(onFulfilled, onRejected) {
    const self = this;
    let bridgePromise;
    onFulfilled = typeof onFulfilled === "function" ? onFulfilled : value => value;
    onRejected = typeof onRejected === "function" ? onRejected : error => { throw error };
    if (self.status === FULFILLED) {
        return bridgePromise = new MyPromise((resolve, reject) => {
            setTimeout(() => {
                try {
                    let x = onFulfilled(self.value);
                    resolvePromise(bridgePromise, x, resolve, reject);
                } catch (e) {
                    reject(e);
                }
            }, 0);
        })
    }
    if (self.status === REJECTED) {
        return bridgePromise = new MyPromise((resolve, reject) => {
            setTimeout(() => {
                try {
                    let x = onRejected(self.error);
                    resolvePromise(bridgePromise, x, resolve, reject);
                } catch (e) {
                    reject(e);
                }
            }, 0);
        });
    }
    if (self.status === PENDING) {
        return bridgePromise = new MyPromise((resolve, reject) => {
            self.onFulfilledCallbacks.push((value) => {
                try {
                    let x = onFulfilled(value);
                    resolvePromise(bridgePromise, x, resolve, reject);
                } catch (e) {
                    reject(e);
                }
            });
            self.onRejectedCallbacks.push((error) => {
                try {
                    let x = onRejected(error);
                    resolvePromise(bridgePromise, x, resolve, reject);
                } catch (e) {
                    reject(e);
                }
            });
        });
    }
}
MyPromise.prototype.catch = function(onRejected) {
    return this.then(null, onRejected);
}
// 执行测试用例需要用到的代码
MyPromise.deferred = function() {
    let defer = {};
    defer.promise = new MyPromise((resolve, reject) => {
        defer.resolve = resolve;
        defer.reject = reject;
    });
    return defer;
}
try {
    module.exports = MyPromise
} catch (e) {}

```

## 7 实现 promise 的all，race，resolve，reject方法

### 7.1 目标

实现es6 promise的all，race，resolve，reject方法

### 7.2 实现

```
MyPromise.all = function(promises) {
    return new MyPromise(function(resolve, reject) {
        let result = [];
        let count = 0;
        for (let i = 0; i < promises.length; i++) {
            promises[i].then(function(data) {
                result[i] = data;
                if (++count == promises.length) {
                    resolve(result);
                }
            }, function(error) {
                reject(error);
            });
        }
    });
}

MyPromise.race = function(promises) {
    return new MyPromise(function(resolve, reject) {
        for (let i = 0; i < promises.length; i++) {
            promises[i].then(function(data) {
                resolve(data);
            }, function(error) {
                reject(error);
            });
        }
    });
}

MyPromise.resolve = function(value) {
    return new MyPromise(resolve => {
        resolve(value);
    });
}

MyPromise.reject = function(error) {
    return new MyPromise((resolve, reject) => {
        reject(error);
    });
}
```

::: tip 参考文章
[一起学习造轮子（一）：从零开始写一个符合Promises/A+规范的promise](https://juejin.cn/post/6844903617619558408)
:::
